[workspace]
members = [
  "crates/*",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
derive-new = "0.7.0"
strum = "0.26.3"
thiserror = "1.0.64"
tracing = "0.1.40"
